print("How old are you?", end = ' ')
age = input()
print("How tall are you?", end = ' ')
height = input()
print("How much do you weight?", end = ' ')
weight = input()
print("What is love?", end = '\t')
love = input()
print("Type an integer: ")
integer = int(input())

print(f"So, you are {age} old, {height} tall and {weight} heavy.")
print(love)
print(integer)
